// Auto-generated by deploy script — do not edit manually
// Deployed at: 2026-06-06T11:10:13.311Z
export const CONTRACT_ADDRESS = "0x610178dA211FEF7D417bC0e6FeD39F05609AD788";
export const WETH_ADDRESS = "0x0165878A594ca255338adfa4d48449f69242Eb8F";
export const USDC_ADDRESS = "0xa513E6E4b8f2a923D98304ec87F64353C4D5C853";
