import { ethers } from "hardhat";
import * as fs from "fs";
import * as path from "path";

async function main() {
  const signer = (await ethers.getSigners())[0];
  console.log("Deploying from account:", signer.address);

  // Deploy Mock FHERC20 tokens
  const MockFHERC20 = await ethers.getContractFactory("MockFHERC20");
  const weth = await MockFHERC20.deploy("FHE Wrapped Ether", "FHE-WETH");
  await weth.waitForDeployment();
  const wethAddress = await weth.getAddress();
  console.log("Mock WETH deployed to:", wethAddress);

  const usdc = await MockFHERC20.deploy("FHE USD Coin", "FHE-USDC");
  await usdc.waitForDeployment();
  const usdcAddress = await usdc.getAddress();
  console.log("Mock USDC deployed to:", usdcAddress);

  // Mint some initial tokens for testing
  await weth.mint(signer.address, 100n);
  await usdc.mint(signer.address, 10000n);
  console.log("Minted mock tokens to deployer.");

  // Deploy OrderBook
  const Factory = await ethers.getContractFactory("PrivateOrderBook");
  const contract = await Factory.deploy(wethAddress, usdcAddress);
  await contract.waitForDeployment();
  const contractAddress = await contract.getAddress();
  console.log("PrivateOrderBook deployed to:", contractAddress);

  // Write addresses to frontend config
  const configContent = `// Auto-generated by deploy script — do not edit manually
// Deployed at: ${new Date().toISOString()}
export const CONTRACT_ADDRESS = "${contractAddress}";
export const WETH_ADDRESS = "${wethAddress}";
export const USDC_ADDRESS = "${usdcAddress}";
`;

  const configPath = path.join(__dirname, "..", "frontend", "src", "config", "contract.ts");
  fs.writeFileSync(configPath, configContent);
  console.log("\nFrontend config updated:", configPath);
  console.log("  CONTRACT_ADDRESS =", contractAddress);
  console.log("  WETH_ADDRESS     =", wethAddress);
  console.log("  USDC_ADDRESS     =", usdcAddress);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
